# Generated by Django 3.2.5 on 2021-07-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0003_phoneimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneImages',
            new_name='PhoneImage',
        ),
    ]
